name: concau
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  http: ^1.4.0
  just_audio: ^0.9.46
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/foto.jpeg" # Ruta de tu imagen

flutter:
  uses-material-design: true

  assets:
    - assets/
